import { SheetWeapon } from "../sheet-weapons/missile";

export const sheetEquipment: SheetWeapon[] = [
  {
    names: ["TAG", "ISTAG", "CLTAG", "TAG(Clan)", "Clan TAG"],
    abbr: "tag",
    heat: 0,
    damage: -1,
    ranges: [0, 5, 9, 15],
  },
  {
    names: ["Guardian ECM", "ISGuardianECM", "ECM Suite", "Guardian ECM Suite"],
    abbr: "ecm",
    heat: 0,
    damage: -1,
    ranges: [0, 0, 0, 6],
  },
  {
    names: [
      "Anti-Missile System",
      "AMS",
      "CLAntiMissileSystem",
      "ISAntiMissileSystem",
    ],
    abbr: "ams",
    heat: 1,
    damage: -1,
    ranges: [0, -1, -1, -1],
  },
  {
    names: ["C3 Computer (Master)", "ISC3MasterComputer"],
    abbr: "c3m",
    heat: 0,
    damage: -1,
    ranges: [0, -1, -1, -1],
  },
  {
    names: ["C3 Computer (Slave)", "ISC3SlaveUnit"],
    abbr: "c3s",
    heat: 0,
    damage: -1,
    ranges: [0, -1, -1, -1],
  },
  {
    names: ["Improved C3 CPU", "ISImprovedC3CPU"],
    abbr: "ic3",
    heat: 0,
    damage: -1,
    ranges: [0, -1, -1, -1],
  },
  {
    names: ["Narc", "ISNarc", "Narc Missile Beacon"],
    abbr: "narc",
    heat: 0,
    damage: -1,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Clan Narc", "CLNarc"],
    abbr: "clnarc",
    heat: 0,
    damage: -1,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["Improved Narc", "ISImprovedNarc"],
    abbr: "in",
    heat: 0,
    damage: -1,
    ranges: [0, 4, 9, 12],
  },
  {
    names: ["Beagle Active Probe", "ISBeagleActiveProbe"],
    abbr: "beagle",
    heat: 0,
    damage: -1,
    ranges: [0, 0, 0, 4],
  },
  {
    names: ["Clan Beagle Active Probe", "CLBeagleActiveProbe"],
    abbr: "clbeagle",
    heat: 0,
    damage: -1,
    ranges: [0, 0, 0, 5],
  },
  {
    names: ["A-Pod", "ISA-Pod"],
    abbr: "apod",
    heat: 0,
    damage: -1,
    ranges: [0, 0, 0, 0],
  },
  {
    names: ["B-Pod", "ISBPod"],
    abbr: "bpod",
    heat: 0,
    damage: -1,
    ranges: [0, 0, 0, 0],
  },
];
