import { SheetWeapon } from "./missile";

export const sheetBallistic: SheetWeapon[] = [
  {
    names: ["AC/2", "ISAC2", "Autocannon/2"],
    abbr: "ac2",
    heat: 1,
    damage: 2,
    ranges: [4, 8, 16, 24],
  },
  {
    names: ["AC/5", "ISAC5", "Autocannon/5"],
    abbr: "ac5",
    heat: 1,
    damage: 5,
    ranges: [3, 6, 12, 18],
  },
  {
    names: ["AC/10", "ISAC10", "Autocannon/10"],
    abbr: "ac10",
    heat: 3,
    damage: 10,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["AC/20", "ISAC20", "Autocannon/20"],
    abbr: "ac20",
    heat: 7,
    damage: 20,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Rotary AC/2", "ISRotaryAC2"],
    abbr: "rotaryac2",
    heat: 1,
    damage: 2,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Rotary AC/5", "ISRotaryAC5"],
    abbr: "rotaryac5",
    heat: 1,
    damage: 5,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["LB 2-X AC", "ISLBXAC2", "Light Ballistic Cannon/2"],
    abbr: "lb2xac",
    heat: 1,
    damage: 2,
    ranges: [4, 9, 18, 27],
  },
  {
    names: ["Clan LB 2-X AC", "CLLBXAC2"],
    abbr: "cllb2xac",
    heat: 1,
    damage: 2,
    ranges: [4, 10, 20, 30],
  },
  {
    names: ["LB 5-X AC", "ISLBXAC5", "Light Ballistic Cannon/5"],
    abbr: "lb5xac",
    heat: 1,
    damage: 5,
    ranges: [3, 8, 14, 21],
  },
  {
    names: ["Clan LB 5-X AC", "CLLBXAC5"],
    abbr: "cllb5xac",
    heat: 1,
    damage: 5,
    ranges: [3, 8, 15, 24],
  },
  {
    names: ["LB 10-X AC", "ISLBXAC10", "Light Ballistic Cannon/10"],
    abbr: "lb10xac",
    heat: 2,
    damage: 10,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Clan LB 10-X AC", "CLLBXAC10"],
    abbr: "cllb10xac",
    heat: 2,
    damage: 10,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["LB 20-X AC", "ISLBXAC20", "Light Ballistic Cannon/20"],
    abbr: "lb20xac",
    heat: 6,
    damage: 20,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["Clan LB 20-X AC", "CLLBXAC20"],
    abbr: "cllb20xac",
    heat: 6,
    damage: 20,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["Light AC/2", "ISLightAC2", "Light Autocannon/2"],
    abbr: "lightac2",
    heat: 1,
    damage: 2,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Light AC/5", "ISLightAC5", "Light Autocannon/5"],
    abbr: "lightac5",
    heat: 1,
    damage: 5,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["Ultra AC/2", "ISUltraAC2"],
    abbr: "ultraac2",
    heat: 1,
    damage: 2,
    ranges: [3, 8, 17, 25],
  },
  {
    names: ["Clan Ultra AC/2", "CLUltraAC2"],
    abbr: "clultraac2",
    heat: 1,
    damage: 2,
    ranges: [2, 9, 18, 27],
  },
  {
    names: ["Ultra AC/5", "ISUltraAC5"],
    abbr: "ultraac5",
    heat: 1,
    damage: 5,
    ranges: [2, 6, 13, 20],
  },
  {
    names: ["Clan Ultra AC/5", "CLUltraAC5"],
    abbr: "clultraac5",
    heat: 1,
    damage: 5,
    ranges: [0, 7, 14, 21],
  },
  {
    names: ["Ultra AC/10", "ISUltraAC10"],
    abbr: "ultraac10",
    heat: 4,
    damage: 10,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Clan Ultra AC/10", "CLUltraAC10"],
    abbr: "clultraac10",
    heat: 3,
    damage: 10,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Ultra AC/20", "ISUltraAC20"],
    abbr: "ultraac20",
    heat: 7,
    damage: 20,
    ranges: [0, 3, 7, 10],
  },
  {
    names: ["Clan Ultra AC/20", "CLUltraAC20"],
    abbr: "clultraac20",
    heat: 6,
    damage: 20,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["Gauss Rifle", "ISGaussRifle", "Clan Gauss Rifle", "CLGaussRifle"],
    abbr: "gaussrifle",
    heat: 1,
    damage: 15,
    ranges: [2, 7, 15, 22],
  },
  {
    names: ["AP Gauss Rifle", "ISAPGaussRifle"],
    abbr: "apgaussrifle",
    heat: 1,
    damage: 3,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Heavy Gauss Rifle", "ISHeavyGaussRifle"],
    abbr: "heavygaussrifle",
    heat: 2,
    damage: 25,
    ranges: [4, 6, 13, 20],
  },
  {
    names: ["Improved Heavy Gauss Rifle", "ISImprovedHeavyGaussRifle"],
    abbr: "improvedheavygaussrifle",
    heat: 2,
    damage: 22,
    ranges: [3, 6, 12, 19],
  },
  {
    names: ["Light Gauss Rifle", "ISLightGaussRifle"],
    abbr: "lightgaussrifle",
    heat: 1,
    damage: 8,
    ranges: [3, 8, 17, 25],
  },
  {
    names: ["Heavy Machine Gun", "ISHeavyMG"],
    abbr: "heavyhmg",
    heat: 0,
    damage: 3,
    ranges: [0, 1, 2, -1],
  },
  {
    names: ["Light Machine Gun", "ISLightMG"],
    abbr: "lightmg",
    heat: 0,
    damage: 1,
    ranges: [0, 2, 4, 6],
  },
  {
    names: ["Machine Gun", "ISMachineGun"],
    abbr: "machinegun",
    heat: 0,
    damage: 2,
    ranges: [0, 1, 2, 3],
  },
  {
    names: [
      "Machine Gun Array",
      "ISMachineGunArray",
      "Clan Machine Gun Array",
      "CLMachineGunArray",
      "ISLMGA",
      "CLMGA",
    ],
    abbr: "machinegunarray",
    heat: 0,
    damage: -1,
    ranges: [-1, -1, -1, -1],
  },
  {
    names: [
      "Heavy Machine Gun Array",
      "ISHMGA",
      "Clan Heavy Machine Gun Array",
      "CLHMGA",
    ],
    abbr: "heavyhmgarray",
    heat: 0,
    damage: -1,
    ranges: [-1, -1, -1, -1],
  },
  {
    names: ["Light Machine Gun Array", "ISLMGA", "CLLMGA"],
    abbr: "lightmgarray",
    heat: 0,
    damage: -1,
    ranges: [-1, -1, -1, -1],
  },
  {
    names: ["Hyper-Assault Gauss Rifle 20", "HAG/20"],
    abbr: "hag20",
    heat: 4,
    damage: 1,
    ranges: [2, 8, 16, 24],
  },
  {
    names: ["Hyper-Assault Gauss Rifle 30", "HAG/30"],
    abbr: "hag30",
    heat: 6,
    damage: 1,
    ranges: [2, 8, 16, 24],
  },
  {
    names: ["Hyper-Assault Gauss Rifle 40", "HAG/40"],
    abbr: "hag40",
    heat: 8,
    damage: 1,
    ranges: [2, 8, 16, 24],
  },
];
