import { SheetWeapon } from "./missile";

export const sheetEnergy: SheetWeapon[] = [
  {
    names: ["Small Laser", "SmallLaser", "ISSmallLaser"],
    abbr: "sl",
    heat: 1,
    damage: 3,
    ranges: [0, 1, 2, 3],
  },
  {
    names: ["Medium Laser", "MediumLaser", "ISMediumLaser"],
    abbr: "ml",
    heat: 3,
    damage: 5,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Large Laser", "LargeLaser", "ISLargeLaser"],
    abbr: "ll",
    heat: 8,
    damage: 8,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["ER Large Laser", "ERLargeLaser", "ISERLargeLaser"],
    abbr: "erll",
    heat: 12,
    damage: 8,
    ranges: [0, 7, 14, 19],
  },
  {
    names: ["Clan ER Large Laser", "CLERLargeLaser"],
    abbr: "clerll",
    heat: 12,
    damage: 10,
    ranges: [0, 8, 15, 25],
  },
  {
    names: ["Clan ER Medium Laser", "CLERMediumLaser"],
    abbr: "clerml",
    heat: 5,
    damage: 7,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["Er Medium Laser", "ERMediumLaser", "ISERMediumLaser"],
    abbr: "erml",
    heat: 5,
    damage: 5,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["ER Small Laser", "ERSmallLaser", "ISERSmallLaser"],
    abbr: "ersl",
    heat: 2,
    damage: 3,
    ranges: [0, 2, 4, 5],
  },
  {
    names: ["Clan ER Small Laser", "CLERSmallLaser"],
    abbr: "clersl",
    heat: 2,
    damage: 3,
    ranges: [0, 2, 4, 6],
  },
  {
    names: ["Large Pulse Laser", "LargePulseLaser", "ISLargePulseLaser"],
    abbr: "lpl",
    heat: 10,
    damage: 9,
    ranges: [0, 3, 7, 10],
  },
  {
    names: ["Clan Large Pulse Laser", "CLLargePulseLaser"],
    abbr: "cllpl",
    heat: 10,
    damage: 10,
    ranges: [0, 6, 14, 20],
  },
  {
    names: ["Medium Pulse Laser", "MediumPulseLaser", "ISMediumPulseLaser"],
    abbr: "mpl",
    heat: 4,
    damage: 6,
    ranges: [0, 2, 4, 6],
  },
  {
    names: ["Clan Medium Pulse Laser", "CLMediumPulseLaser"],
    abbr: "clmpl",
    heat: 4,
    damage: 7,
    ranges: [0, 4, 8, 12],
  },
  {
    names: ["Small Pulse Laser", "SmallPulseLaser", "ISSmallPulseLaser"],
    abbr: "spl",
    heat: 2,
    damage: 3,
    ranges: [0, 1, 2, 3],
  },
  {
    names: ["Clan Small Pulse Laser", "CLSmallPulseLaser"],
    abbr: "clspl",
    heat: 2,
    damage: 3,
    ranges: [0, 2, 4, 6],
  },
  {
    names: ["Large X-Pulse Laser", "LargeXPulseLaser", "ISLargeXPulseLaser"],
    abbr: "lxpl",
    heat: 14,
    damage: 9,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["Medium X-Pulse Laser", "MediumXPulseLaser", "ISMediumXPulseLaser"],
    abbr: "mxpl",
    heat: 6,
    damage: 6,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Small X-Pulse Laser", "SmallXPulseLaser", "ISSmallXPulseLaser"],
    abbr: "sxpl",
    heat: 3,
    damage: 3,
    ranges: [0, 2, 4, 5],
  },
  {
    names: ["Clan ER Large Pulse Laser", "CLERLargePulseLaser"],
    abbr: "erlpl",
    heat: 13,
    damage: 10,
    ranges: [0, 7, 15, 23],
  },
  {
    names: ["Clan ER Medium Pulse Laser", "CLERMediumPulseLaser"],
    abbr: "ermpl",
    heat: 6,
    damage: 7,
    ranges: [0, 5, 9, 14],
  },
  {
    names: ["Clan ER Small Pulse Laser", "CLERSmallPulseLaser"],
    abbr: "erspl",
    heat: 3,
    damage: 5,
    ranges: [0, 2, 4, 6],
  },
  {
    names: ["ER Micro Laser", "ERMicroLaser"],
    abbr: "ermicl",
    heat: 1,
    damage: 2,
    ranges: [0, 1, 2, 4],
  },
  {
    names: ["PPC", "ISPPC", "Partical Projection Cannon"],
    abbr: "ppc",
    heat: 10,
    damage: 10,
    ranges: [3, 6, 12, 18],
  },
  {
    names: ["ER PPC", "ERPPC", "ISERPPC"],
    abbr: "erppc",
    heat: 15,
    damage: 10,
    ranges: [0, 7, 14, 23],
  },
  {
    names: ["Clan ER PPC", "CLERPPC"],
    abbr: "clerppc",
    heat: 15,
    damage: 15,
    ranges: [0, 7, 14, 23],
  },
  {
    names: ["Light PPC", "ISLightPPC"],
    abbr: "lppc",
    heat: 5,
    damage: 5,
    ranges: [3, 6, 12, 18],
  },
  {
    names: ["Heavy PPC", "ISHeavyPPC"],
    abbr: "hppc",
    heat: 15,
    damage: 15,
    ranges: [3, 6, 12, 18],
  },
  {
    names: ["Snub-Nose PPC", "ISSnubNosePPC"],
    abbr: "snppc",
    heat: 10,
    damage: 10,
    ranges: [0, 9, 13, 15],
  },
  {
    names: ["Plasma Cannon", "PlasmaCannon", "ClanPlasmaCannon"],
    abbr: "plc",
    heat: 7,
    damage: -1,
    ranges: [0, 6, 12, 18],
  },
  {
    names: ["Plasma Rifle", "PlasmaRifle", "ISPlasmaRifle"],
    abbr: "plr",
    heat: 10,
    damage: 10,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["Heavy Large Laser", "HeavyLargeLaser", "CLHeavyLargeLaser"],
    abbr: "hll",
    heat: 18,
    damage: 16,
    ranges: [0, 5, 10, 15],
  },
  {
    names: ["Heavy Medium Laser", "HeavyMediumLaser", "CLHeavyMediumLaser"],
    abbr: "hml",
    heat: 7,
    damage: 10,
    ranges: [0, 3, 6, 9],
  },
  {
    names: ["Heavy Small Laser", "HeavySmallLaser", "CLHeavySmallLaser"],
    abbr: "hsl",
    heat: 3,
    damage: 6,
    ranges: [0, 1, 2, 3],
  },
  {
    names: ["Flamer", "ISFlamer", "Clan Flamer", "CLFlamer"],
    abbr: "fl",
    heat: 3,
    damage: 2,
    ranges: [0, 1, 2, 3],
  },
  {
    names: ["TSEMP", "ISTSEMP", "TSEMP Cannon"],
    abbr: "tsemp",
    heat: 10,
    damage: 0,
    ranges: [0, 5, 9, 15],
  },
];
